# config.yml

# Default number of suggestions a player can make (set on first join)
default-suggestions-limit: 2

# GUI settings
gui:

  #player menu titles
  own-suggestions-title: "&dYour Suggestions"
  player-menu-title: "&9SuggestionsX  &3Main Menu"
  server-suggestions-title: "&9Server Suggestions"

  #admin menu titles
  admin-menu-title: "&9SuggestionsX  &3Main Menu  &cADMIN"
  pending-menu-title: "&6Pending Suggestions  &cADMIN"
  admin-suggestions-title: "&9Server Suggestions  &cADMIN"
